- hosts: all
  tasks:
    - name: Copy inception files on ec2 instances
      ansible.builtin.copy:
        src: ~/files/
        dest: /home/ubuntu/
        mode: '0755'
        owner: ubuntu
        group: ubuntu
