- name: Install dependencies
  hosts: all
  become: true
  tasks:
    - name: Install make, ca-certificates
      ansible.builtin.package:
        name:
          - ca-certificates
          - make
          - apt-transport-https
          - curl
        state: present
    
    - name: Add docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Update apt and install docker-certificates
      ansible.builtin.apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add ansible user to Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create docker CLI directory
      ansible.builtin.file:
        path: "/usr/local/lib/docker/cli-plugins"
        state: directory
        mode: '0755'

    - name: Download docker compose plugin
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/v2.39.2/docker-compose-linux-{{ ansible_architecture }}"
        dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
        mode: '0755'
